package com.supercarlounge.supercar.enumset

enum class GuidePopType {
    GUIDE_DRIVE_VIEW,GUIDE_DRIVE_WRITE,GUIDE_VIP_LOUNGE,GUIDE_BOARD,GUIDE_BOARD_WRITE,GUIDE_MY_CAR_BOARD,GUIDE_MY_CAR_BOARD_POST,LOCATION,MY_PAGE
}