package com.supercarlounge.supercar.enumset

enum class PopTypeStatus {
    POST_BLOCK,POST_POLICE,COMMENT_BLOCK,PROFLIE_BLOCK,PROFILE_POLICE,DRIVE_BLOCK,DRIVE_POLICE,DRIVE_DELETE,COMMENT_DELETE,POST_DELETE
    ,DRIVE_FRIEND,DRIVE_NOT_FRIEND,POST_FRIEND,POST_NOT_FRIEND,USER_EDIT_CHECK
}

enum class ConfirmStatus {
    PROFILE_CONFIRM,CRUSH_CONFIRM,PROFILE_EDIT
}



